package com.sqx.bean;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.id
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.empname
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.gender
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.email
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.login_account
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    private String loginAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.id
     *
     * @return the value of t_employee.id
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.id
     *
     * @param id the value for t_employee.id
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.empname
     *
     * @return the value of t_employee.empname
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.empname
     *
     * @param empname the value for t_employee.empname
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.gender
     *
     * @return the value of t_employee.gender
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.gender
     *
     * @param gender the value for t_employee.gender
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.email
     *
     * @return the value of t_employee.email
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.email
     *
     * @param email the value for t_employee.email
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.login_account
     *
     * @return the value of t_employee.login_account
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.login_account
     *
     * @param loginAccount the value for t_employee.login_account
     *
     * @mbggenerated Thu Nov 19 21:09:45 CST 2020
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }
}